name: Automatic Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@99b0226479c59e6a40092b8afe704aabc61dec09 # 1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
