name: CI

on:
  - pull_request
  - push

jobs:
  test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.7.x
            os: ubuntu-18.04
            otp: 19.x
          
          - elixir: 1.7.x
            otp: 20.x

          - elixir: 1.7.x
            otp: 21.x

          - elixir: 1.7.x
            otp: 22.x

          - elixir: 1.8.x
            otp: 20.x

          - elixir: 1.8.x
            otp: 21.x

          - elixir: 1.8.x
            otp: 22.x

          - elixir: 1.9.x
            otp: 20.x

          - elixir: 1.9.x
            otp: 21.x

          - elixir: 1.9.x
            otp: 22.x

          - elixir: 1.10.x
            otp: 21.x

          - elixir: 1.10.x
            otp: 22.x

          - elixir: 1.11.x
            otp: 21.x

          - elixir: 1.11.x
            otp: 22.x

          - elixir: 1.11.x
            otp: 23.x

          - elixir: 1.12.x
            otp: 22.x

          - elixir: 1.12.x
            otp: 23.x

          - elixir: 1.12.x
            otp: 24.x

    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.2

      - name: Setup cache
        uses: actions/cache@v2.1.6
        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-1
          path: _build

      - name: Install runtime
        uses: erlef/setup-beam@v1.9.0
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
