name: CI

on:
  - pull_request
  - push

jobs:
  test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.x
            otp: 21.x
            os: ubuntu-20.04
          - elixir: 1.11.x
            otp: 22.x
            os: ubuntu-20.04
          - elixir: 1.11.x
            otp: 23.x
            os: ubuntu-20.04
          - elixir: 1.12.x
            otp: 22.x
            os: ubuntu-20.04
          - elixir: 1.12.x
            otp: 23.x
            os: ubuntu-20.04
          - elixir: 1.12.x
            otp: 24.x
            os: ubuntu-20.04
          - elixir: 1.13.x
            otp: 22.x
            os: ubuntu-20.04
          - elixir: 1.13.x
            otp: 23.x
            os: ubuntu-20.04
          - elixir: 1.13.x
            otp: 24.x
            os: ubuntu-20.04
          - elixir: 1.14.x
            otp: 23.x
            os: ubuntu-20.04
          - elixir: 1.14.x
            otp: 24.x
            os: ubuntu-20.04
          - elixir: 1.14.x
            otp: 25.x
            os: ubuntu-20.04
          - elixir: 1.15.x
            otp: 24.x
            os: ubuntu-20.04
          - elixir: 1.15.x
            otp: 25.x
            os: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Setup cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}-1
          path: _build

      - name: Install runtime
        uses: erlef/setup-beam@0a541161e47ec43ccbd9510053c5f336ca76c2a2 # v1.17.6
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
